# STATUS: NOT WORKING AS OF NOW
version: "3.7"
services:
  app:
    image: ros_melodic_complete:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/root/catkin_ws
    network_mode: "host"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
    #command: ['--gpus all']
    env_file:
      - ./.env

# Use docker-compose up
# you have to use docker exec <containername> /bin/bash